name: Publish Nightly

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Dotnet
      run: dotnet build --no-restore --warnaserror
    - name: "JPRM: Build"
      id: jrpm
      uses: oddstr13/jellyfin-plugin-repository-manager@master
      with:
        verbosity: debug
        path: .
        dotnet-target: "net6.0"
        output: _dist
    - run: mkdir -p _repo && cp manifest.json _repo/
    - name: List Output Artifact
      run: 'ls -la _dist _repo'    

    - name: Publish output artifacts
      id: publish-assets
      uses: softprops/action-gh-release@50195ba7f6f93d1ac97ba8332a178e008ad176aa
      with:
          prerelease: true
          fail_on_unmatched_files: true
          tag_name: nightly
          files: |
            _dist/*
          body: |
            Nightly build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Get Assets as json"
      run: "echo ${{ steps.publish-assets.outputs.assets }} > assets.json"
    - name: Extract artifact url
      uses: sergeysova/jq-action@v2
      id: artifact-url
      with:
        cmd: |
          jq '.[] | select(.content_type=="application/zip") | .browser_download_url' assets.json --raw-output
    - name: Echo artifcat url
      run: |
        cat assets.json
        echo ${{ steps.artifact-url.outputs.value }}
    - name: "JPRM: Repo"
      run: 'python3 /home/runner/work/_actions/oddstr13/jellyfin-plugin-repository-manager/master/jprm/__init__.py repo add --url="${{ steps.artifact-url.outputs.value }}" _repo _dist/*.zip'
    - name: List Output Artifact
      run: 'ls -la _dist _repo'     
    - name: Copy manifest to output
      run: cp _repo/manifest.json _dist/
    - name: Publish output artifacts
      uses: softprops/action-gh-release@50195ba7f6f93d1ac97ba8332a178e008ad176aa
      with:
          prerelease: true
          fail_on_unmatched_files: true
          tag_name: nightly
          files: |
            _repo/*.json
          body: |
            Nightly build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}